name: Build HA Add-on Images

on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "public/**"
      - "server/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.ts"
      - "tsconfig*.json"
      - "index.html"
      - "gilberts-todo/Dockerfile"
      - "gilberts-todo/config.yaml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ghcr.io/gilbert-grape/gilberts-to-do-list

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, amd64, armv7, i386]
        include:
          - arch: aarch64
            platform: linux/arm64
          - arch: amd64
            platform: linux/amd64
          - arch: armv7
            platform: linux/arm/v7
          - arch: i386
            platform: linux/386
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from config.yaml
        id: version
        run: |
          version=$(grep '^version:' gilberts-todo/config.yaml | sed 's/version: *"\?\([^"]*\)"\?/\1/')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: gilberts-todo/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}/${{ matrix.arch }}-gilberts-todo:${{ steps.version.outputs.version }}
            ${{ env.IMAGE_BASE }}/${{ matrix.arch }}-gilberts-todo:latest
          cache-from: type=gha,scope=${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.arch }}
